export const playerPoolCompleto = [
  { nome: "Malen", squadra: "ROMA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 58, fvm: 219, quot: 37, motivo: "FVM 219 Quot 37" },
  { nome: "Martinez L.", squadra: "INTER", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 56, fvm: 209, quot: 36, motivo: "FVM 209 Quot 36" },
  { nome: "Thuram", squadra: "INTER", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 44, fvm: 138, quot: 31, motivo: "FVM 138 Quot 31" },
  { nome: "Paz N.", squadra: "COMO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 41, fvm: 124, quot: 29, motivo: "FVM 124 Quot 29" },
  { nome: "Hojlund", squadra: "NAPOLI", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 39, fvm: 120, quot: 27, motivo: "FVM 120 Quot 27" },
  { nome: "Ramos G.", squadra: "MILAN", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 36, fvm: 119, quot: 25, motivo: "FVM 119 Quot 25" },
  { nome: "Calhanoglu", squadra: "INTER", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 38, fvm: 110, quot: 27, motivo: "FVM 110 Quot 27" },
  { nome: "Dimarco", squadra: "INTER", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 39, fvm: 105, quot: 29, motivo: "FVM 105 Quot 29" },
  { nome: "Baturina", squadra: "COMO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 28, fvm: 77, quot: 21, motivo: "FVM 77 Quot 21" },
  { nome: "Pulisic", squadra: "MILAN", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 32, fvm: 75, quot: 25, motivo: "FVM 75 Quot 25" },
  { nome: "Rabiot", squadra: "MILAN", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 31, fvm: 71, quot: 24, motivo: "FVM 71 Quot 24" },
  { nome: "Douvikas", squadra: "COMO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 28, fvm: 69, quot: 22, motivo: "FVM 69 Quot 22" },
  { nome: "Kean", squadra: "COMO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 29, fvm: 69, quot: 23, motivo: "FVM 69 Quot 23" },
  { nome: "Orsolini", squadra: "BOLOGNA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 29, fvm: 69, quot: 23, motivo: "FVM 69 Quot 23" },
  { nome: "Kolo Muani", squadra: "JUVENTUS", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 29, fvm: 61, quot: 23, motivo: "FVM 61 Quot 23" },
  { nome: "Zaccagni", squadra: "LAZIO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 24, fvm: 61, quot: 18, motivo: "FVM 61 Quot 18" },
  { nome: "Dybala", squadra: "ROMA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 23, fvm: 60, quot: 17, motivo: "FVM 60 Quot 17" },
  { nome: "McTominay", squadra: "NAPOLI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 30, fvm: 60, quot: 24, motivo: "FVM 60 Quot 24" },
  { nome: "Davis K.", squadra: "UDINESE", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 24, fvm: 57, quot: 19, motivo: "FVM 57 Quot 19" },
  { nome: "Frattesi", squadra: "LAZIO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 57, quot: 12, motivo: "FVM 57 Quot 12" },
  { nome: "Esposito F.P.", squadra: "INTER", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 23, fvm: 54, quot: 18, motivo: "FVM 54 Quot 18" },
  { nome: "Berardi", squadra: "SASSUOLO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 23, fvm: 52, quot: 18, motivo: "FVM 52 Quot 18" },
  { nome: "Scamacca", squadra: "ATALANTA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 24, fvm: 50, quot: 19, motivo: "FVM 50 Quot 19" },
  { nome: "Woltemade", squadra: "JUVENTUS", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 26, fvm: 49, quot: 22, motivo: "FVM 49 Quot 22" },
  { nome: "Wesley", squadra: "ROMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 22, fvm: 47, quot: 18, motivo: "FVM 47 Quot 18" },
  { nome: "De Bruyne", squadra: "NAPOLI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 21, fvm: 45, quot: 17, motivo: "FVM 45 Quot 17" },
  { nome: "Svilar", squadra: "ROMA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 23, fvm: 45, quot: 19, motivo: "FVM 45 Quot 19" },
  { nome: "Barella", squadra: "INTER", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 22, fvm: 42, quot: 18, motivo: "FVM 42 Quot 18" },
  { nome: "Krstovic", squadra: "ATALANTA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 40, quot: 16, motivo: "FVM 40 Quot 16" },
  { nome: "Bremer", squadra: "JUVENTUS", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 21, fvm: 40, quot: 17, motivo: "FVM 40 Quot 17" },
  { nome: "Laurientè", squadra: "SASSUOLO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 39, quot: 16, motivo: "FVM 39 Quot 16" },
  { nome: "Leao", squadra: "MILAN", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 21, fvm: 38, quot: 18, motivo: "FVM 38 Quot 18" },
  { nome: "Zaniolo", squadra: "UDINESE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 36, quot: 16, motivo: "FVM 36 Quot 16" },
  { nome: "Varela G.", squadra: "MONZA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 35, quot: 10, motivo: "FVM 35 Quot 10" },
  { nome: "Yildiz", squadra: "JUVENTUS", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 23, fvm: 35, quot: 20, motivo: "FVM 35 Quot 20" },
  { nome: "Mastantuono", squadra: "FIORENTINA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 35, quot: 14, motivo: "FVM 35 Quot 14" },
  { nome: "Conceicao", squadra: "JUVENTUS", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 35, quot: 14, motivo: "FVM 35 Quot 14" },
  { nome: "Da Cunha", squadra: "COMO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 35, quot: 17, motivo: "FVM 35 Quot 17" },
  { nome: "Diao", squadra: "COMO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 34, quot: 14, motivo: "FVM 34 Quot 14" },
  { nome: "Mora", squadra: "ROMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 23, fvm: 33, quot: 20, motivo: "FVM 33 Quot 20" },
  { nome: "Molina N.", squadra: "ROMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 33, quot: 17, motivo: "FVM 33 Quot 17" },
  { nome: "Vicario", squadra: "JUVENTUS", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 33, quot: 16, motivo: "FVM 33 Quot 16" },
  { nome: "De Ketelaere", squadra: "ATALANTA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 32, quot: 15, motivo: "FVM 32 Quot 15" },
  { nome: "Soulè", squadra: "ROMA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 32, quot: 16, motivo: "FVM 32 Quot 16" },
  { nome: "Atta", squadra: "FIORENTINA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 32, quot: 14, motivo: "FVM 32 Quot 14" },
  { nome: "Ekkelenkamp", squadra: "UDINESE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 32, quot: 14, motivo: "FVM 32 Quot 14" },
  { nome: "Martinez Jo.", squadra: "INTER", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 32, quot: 14, motivo: "FVM 32 Quot 14" },
  { nome: "McKennie", squadra: "JUVENTUS", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 31, quot: 15, motivo: "FVM 31 Quot 15" },
  { nome: "Raimondo", squadra: "FROSINONE", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 30, quot: 12, motivo: "FVM 30 Quot 12" },
  { nome: "Moreira", squadra: "MILAN", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 30, quot: 15, motivo: "FVM 30 Quot 15" },
  { nome: "Simeone", squadra: "TORINO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 29, quot: 13, motivo: "FVM 29 Quot 13" },
  { nome: "Vlasic", squadra: "TORINO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 29, quot: 11, motivo: "FVM 29 Quot 11" },
  { nome: "Diouf", squadra: "INTER", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 28, quot: 11, motivo: "FVM 28 Quot 11" },
  { nome: "Carnesecchi", squadra: "ATALANTA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 28, quot: 16, motivo: "FVM 28 Quot 16" },
  { nome: "Colombo", squadra: "GENOA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 27, quot: 10, motivo: "FVM 27 Quot 10" },
  { nome: "Rrahmani", squadra: "NAPOLI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 27, quot: 15, motivo: "FVM 27 Quot 15" },
  { nome: "Mancini", squadra: "ROMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 27, quot: 15, motivo: "FVM 27 Quot 15" },
  { nome: "Maignan", squadra: "MILAN", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 27, quot: 15, motivo: "FVM 27 Quot 15" },
  { nome: "Pellegrino M.", squadra: "FIORENTINA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 26, quot: 16, motivo: "FVM 26 Quot 16" },
  { nome: "Kvernadze", squadra: "FROSINONE", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 25, quot: 11, motivo: "FVM 25 Quot 11" },
  { nome: "Beto", squadra: "FIORENTINA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 25, quot: 13, motivo: "FVM 25 Quot 13" },
  { nome: "Konè M.", squadra: "ROMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 25, quot: 14, motivo: "FVM 25 Quot 14" },
  { nome: "Pavlovic", squadra: "MILAN", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 25, quot: 13, motivo: "FVM 25 Quot 13" },
  { nome: "Maldini", squadra: "CAGLIARI", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 23, quot: 11, motivo: "FVM 23 Quot 11" },
  { nome: "Lukaku", squadra: "NAPOLI", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 23, quot: 10, motivo: "FVM 23 Quot 10" },
  { nome: "Ederson D.S.", squadra: "ATALANTA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 23, quot: 13, motivo: "FVM 23 Quot 13" },
  { nome: "Gonzalez N.", squadra: "JUVENTUS", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 23, quot: 13, motivo: "FVM 23 Quot 13" },
  { nome: "Tavares N.", squadra: "LAZIO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 23, quot: 9, motivo: "FVM 23 Quot 9" },
  { nome: "Romero D.", squadra: "PARMA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 22, quot: 13, motivo: "FVM 22 Quot 13" },
  { nome: "Taylor K.", squadra: "LAZIO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 22, quot: 13, motivo: "FVM 22 Quot 13" },
  { nome: "Butez", squadra: "COMO", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 22, quot: 13, motivo: "FVM 22 Quot 13" },
  { nome: "Esposito Se.", squadra: "SASSUOLO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 21, quot: 14, motivo: "FVM 21 Quot 14" },
  { nome: "Piccoli", squadra: "BOLOGNA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 21, quot: 9, motivo: "FVM 21 Quot 9" },
  { nome: "Politano", squadra: "NAPOLI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 21, quot: 11, motivo: "FVM 21 Quot 11" },
  { nome: "Zielinski", squadra: "INTER", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 21, quot: 13, motivo: "FVM 21 Quot 13" },
  { nome: "Kalulu", squadra: "JUVENTUS", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 21, quot: 13, motivo: "FVM 21 Quot 13" },
  { nome: "Akanji", squadra: "INTER", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 21, quot: 14, motivo: "FVM 21 Quot 14" },
  { nome: "Mandas", squadra: "LAZIO", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 21, quot: 13, motivo: "FVM 21 Quot 13" },
  { nome: "Castro S.", squadra: "ROMA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 20, quot: 13, motivo: "FVM 20 Quot 13" },
  { nome: "Pinamonti", squadra: "LAZIO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 20, quot: 10, motivo: "FVM 20 Quot 10" },
  { nome: "Alajbegovic", squadra: "JUVENTUS", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 20, quot: 11, motivo: "FVM 20 Quot 11" },
  { nome: "Modric", squadra: "MILAN", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 20, quot: 12, motivo: "FVM 20 Quot 12" },
  { nome: "Mandragora", squadra: "TORINO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 20, quot: 12, motivo: "FVM 20 Quot 12" },
  { nome: "Bastoni", squadra: "INTER", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 20, quot: 13, motivo: "FVM 20 Quot 13" },
  { nome: "Meret", squadra: "NAPOLI", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 20, quot: 9, motivo: "FVM 20 Quot 9" },
  { nome: "Santos A.", squadra: "NAPOLI", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 19, quot: 13, motivo: "FVM 19 Quot 13" },
  { nome: "Goncalves P.", squadra: "FIORENTINA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 19, quot: 11, motivo: "FVM 19 Quot 11" },
  { nome: "Schmid", squadra: "FROSINONE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 19, quot: 11, motivo: "FVM 19 Quot 11" },
  { nome: "Calò", squadra: "FROSINONE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 19, quot: 11, motivo: "FVM 19 Quot 11" },
  { nome: "Adzic", squadra: "SASSUOLO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 19, quot: 11, motivo: "FVM 19 Quot 11" },
  { nome: "Gudmundsson A.", squadra: "LAZIO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 19, quot: 13, motivo: "FVM 19 Quot 13" },
  { nome: "Di Lorenzo", squadra: "NAPOLI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 19, quot: 12, motivo: "FVM 19 Quot 12" },
  { nome: "Osmajic", squadra: "GENOA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 18, quot: 10, motivo: "FVM 18 Quot 10" },
  { nome: "Noslin", squadra: "LAZIO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 18, quot: 10, motivo: "FVM 18 Quot 10" },
  { nome: "Rowe", squadra: "ATALANTA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 18, quot: 9, motivo: "FVM 18 Quot 9" },
  { nome: "Samardzic", squadra: "ATALANTA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 18, quot: 14, motivo: "FVM 18 Quot 14" },
  { nome: "Bernardeschi", squadra: "BOLOGNA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 18, quot: 12, motivo: "FVM 18 Quot 12" },
  { nome: "Hermoso", squadra: "ROMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 18, quot: 12, motivo: "FVM 18 Quot 12" },
  { nome: "Adams A.", squadra: "VENEZIA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 17, quot: 12, motivo: "FVM 17 Quot 12" },
  { nome: "Bowie", squadra: "SASSUOLO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 17, quot: 12, motivo: "FVM 17 Quot 12" },
  { nome: "Dovbyk", squadra: "BOLOGNA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 17, quot: 15, motivo: "FVM 17 Quot 15" },
  { nome: "Cissè A.", squadra: "MILAN", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 17, quot: 6, motivo: "FVM 17 Quot 6" },
  { nome: "Jones C.", squadra: "INTER", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 17, quot: 12, motivo: "FVM 17 Quot 12" },
  { nome: "Kessiè", squadra: "ATALANTA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 17, quot: 11, motivo: "FVM 17 Quot 11" },
  { nome: "Ramon", squadra: "COMO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 17, quot: 12, motivo: "FVM 17 Quot 12" },
  { nome: "Bisseck", squadra: "INTER", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 17, quot: 13, motivo: "FVM 17 Quot 13" },
  { nome: "Ghedjemis", squadra: "FROSINONE", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 16, quot: 11, motivo: "FVM 16 Quot 11" },
  { nome: "Tourè E.", squadra: "PARMA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 16, quot: 10, motivo: "FVM 16 Quot 10" },
  { nome: "Perrone", squadra: "COMO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 16, quot: 11, motivo: "FVM 16 Quot 11" },
  { nome: "Thorstvedt", squadra: "SASSUOLO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 16, quot: 9, motivo: "FVM 16 Quot 9" },
  { nome: "Saelemaekers", squadra: "MILAN", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 16, quot: 11, motivo: "FVM 16 Quot 11" },
  { nome: "Cristante", squadra: "ROMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 16, quot: 11, motivo: "FVM 16 Quot 11" },
  { nome: "NDicka", squadra: "ROMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 16, quot: 11, motivo: "FVM 16 Quot 11" },
  { nome: "Raspadori", squadra: "ATALANTA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 15, quot: 14, motivo: "FVM 15 Quot 14" },
  { nome: "Pisilli", squadra: "ROMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 15, quot: 9, motivo: "FVM 15 Quot 9" },
  { nome: "Solet", squadra: "UDINESE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 15, quot: 12, motivo: "FVM 15 Quot 12" },
  { nome: "Couto", squadra: "COMO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 15, quot: 8, motivo: "FVM 15 Quot 8" },
  { nome: "Jimenez A.", squadra: "FIORENTINA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 15, quot: 10, motivo: "FVM 15 Quot 10" },
  { nome: "Gila", squadra: "MILAN", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 15, quot: 13, motivo: "FVM 15 Quot 13" },
  { nome: "Caprile", squadra: "CAGLIARI", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 15, quot: 13, motivo: "FVM 15 Quot 13" },
  { nome: "Yeboah J.", squadra: "VENEZIA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 14, quot: 8, motivo: "FVM 14 Quot 8" },
  { nome: "Njie", squadra: "FIORENTINA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 14, quot: 7, motivo: "FVM 14 Quot 7" },
  { nome: "Bernabè", squadra: "PARMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 14, quot: 6, motivo: "FVM 14 Quot 6" },
  { nome: "Lobotka", squadra: "NAPOLI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 14, quot: 11, motivo: "FVM 14 Quot 11" },
  { nome: "Zambo Anguissa", squadra: "NAPOLI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 14, quot: 9, motivo: "FVM 14 Quot 9" },
  { nome: "Carlos Augusto", squadra: "INTER", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 14, quot: 10, motivo: "FVM 14 Quot 10" },
  { nome: "Vasquez", squadra: "GENOA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 14, quot: 9, motivo: "FVM 14 Quot 9" },
  { nome: "Adams C.", squadra: "TORINO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 13, quot: 11, motivo: "FVM 13 Quot 11" },
  { nome: "David", squadra: "JUVENTUS", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 13, quot: 8, motivo: "FVM 13 Quot 8" },
  { nome: "Milla", squadra: "COMO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 13, quot: 7, motivo: "FVM 13 Quot 7" },
  { nome: "Vergara", squadra: "NAPOLI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 13, quot: 9, motivo: "FVM 13 Quot 9" },
  { nome: "Cacciamani", squadra: "TORINO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 13, quot: 8, motivo: "FVM 13 Quot 8" },
  { nome: "Fazzini", squadra: "CAGLIARI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 13, quot: 7, motivo: "FVM 13 Quot 7" },
  { nome: "Mangas", squadra: "MONZA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 13, quot: 10, motivo: "FVM 13 Quot 10" },
  { nome: "Ostigard", squadra: "GENOA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 13, quot: 10, motivo: "FVM 13 Quot 10" },
  { nome: "Chalobah T.", squadra: "COMO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 13, quot: 9, motivo: "FVM 13 Quot 9" },
  { nome: "Gutierrez", squadra: "NAPOLI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 13, quot: 8, motivo: "FVM 13 Quot 8" },
  { nome: "Alaba", squadra: "UDINESE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 13, quot: 10, motivo: "FVM 13 Quot 10" },
  { nome: "Okoye", squadra: "UDINESE", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 13, quot: 8, motivo: "FVM 13 Quot 8" },
  { nome: "De Gea", squadra: "FIORENTINA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 13, quot: 10, motivo: "FVM 13 Quot 10" },
  { nome: "Rodriguez Je.", squadra: "COMO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 12, quot: 11, motivo: "FVM 12 Quot 11" },
  { nome: "Sarr P.", squadra: "JUVENTUS", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 12, quot: 7, motivo: "FVM 12 Quot 7" },
  { nome: "Chukwueze", squadra: "MILAN", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 12, quot: 10, motivo: "FVM 12 Quot 10" },
  { nome: "Gaetano", squadra: "ATALANTA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 12, quot: 6, motivo: "FVM 12 Quot 6" },
  { nome: "De Winter", squadra: "MILAN", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 12, quot: 6, motivo: "FVM 12 Quot 6" },
  { nome: "Scalvini", squadra: "ATALANTA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 12, quot: 10, motivo: "FVM 12 Quot 10" },
  { nome: "Falcone", squadra: "LECCE", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 12, quot: 7, motivo: "FVM 12 Quot 7" },
  { nome: "Skorupski", squadra: "BOLOGNA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 12, quot: 9, motivo: "FVM 12 Quot 9" },
  { nome: "Ratkov", squadra: "LAZIO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 11, quot: 9, motivo: "FVM 11 Quot 9" },
  { nome: "Boga", squadra: "JUVENTUS", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 11, quot: 6, motivo: "FVM 11 Quot 6" },
  { nome: "Romano", squadra: "CAGLIARI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 11, quot: 10, motivo: "FVM 11 Quot 10" },
  { nome: "Isaksen", squadra: "LAZIO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 11, quot: 8, motivo: "FVM 11 Quot 8" },
  { nome: "Ferguson", squadra: "BOLOGNA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 11, quot: 8, motivo: "FVM 11 Quot 8" },
  { nome: "Baldanzi", squadra: "GENOA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 11, quot: 10, motivo: "FVM 11 Quot 10" },
  { nome: "Zhegrova", squadra: "JUVENTUS", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 11, quot: 10, motivo: "FVM 11 Quot 10" },
  { nome: "Cancellieri", squadra: "LAZIO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 11, quot: 11, motivo: "FVM 11 Quot 11" },
  { nome: "Fagioli", squadra: "FIORENTINA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 11, quot: 8, motivo: "FVM 11 Quot 8" },
  { nome: "Cambiaghi", squadra: "BOLOGNA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 11, quot: 8, motivo: "FVM 11 Quot 8" },
  { nome: "Tiago Gabriel", squadra: "LECCE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 11, quot: 9, motivo: "FVM 11 Quot 9" },
  { nome: "Delprato", squadra: "PARMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 11, quot: 8, motivo: "FVM 11 Quot 8" },
  { nome: "Valeri", squadra: "PARMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 11, quot: 9, motivo: "FVM 11 Quot 9" },
  { nome: "Miranda J.", squadra: "BOLOGNA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 11, quot: 10, motivo: "FVM 11 Quot 10" },
  { nome: "Spinazzola", squadra: "NAPOLI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 11, quot: 8, motivo: "FVM 11 Quot 8" },
  { nome: "Palmisani", squadra: "FROSINONE", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 11, quot: 9, motivo: "FVM 11 Quot 9" },
  { nome: "Zeballos", squadra: "MONZA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 7, motivo: "FVM 10 Quot 7" },
  { nome: "Kevin Carlos", squadra: "CAGLIARI", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 10, motivo: "FVM 10 Quot 10" },
  { nome: "Mendy P.", squadra: "CAGLIARI", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 8, motivo: "FVM 10 Quot 8" },
  { nome: "Dia", squadra: "LAZIO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 10, motivo: "FVM 10 Quot 10" },
  { nome: "Nkunku", squadra: "MILAN", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 13, motivo: "FVM 10 Quot 13" },
  { nome: "Monteiro J.", squadra: "LECCE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 6, motivo: "FVM 10 Quot 6" },
  { nome: "Sucic P.", squadra: "INTER", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 9, motivo: "FVM 10 Quot 9" },
  { nome: "Konè I.", squadra: "SASSUOLO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 7, motivo: "FVM 10 Quot 7" },
  { nome: "Karlstrom", squadra: "UDINESE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 9, motivo: "FVM 10 Quot 9" },
  { nome: "Ndour", squadra: "FIORENTINA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 8, motivo: "FVM 10 Quot 8" },
  { nome: "Frendrup", squadra: "GENOA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 7, motivo: "FVM 10 Quot 7" },
  { nome: "Volpato", squadra: "SASSUOLO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 9, motivo: "FVM 10 Quot 9" },
  { nome: "Sutalo J.", squadra: "LAZIO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 7, motivo: "FVM 10 Quot 7" },
  { nome: "Valle", squadra: "COMO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 8, motivo: "FVM 10 Quot 8" },
  { nome: "Theate", squadra: "BOLOGNA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 8, motivo: "FVM 10 Quot 8" },
  { nome: "Dragusin", squadra: "FIORENTINA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 8, motivo: "FVM 10 Quot 8" },
  { nome: "Romagnoli", squadra: "LAZIO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 6, motivo: "FVM 10 Quot 6" },
  { nome: "Suzuki", squadra: "PARMA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 10, quot: 7, motivo: "FVM 10 Quot 7" },
  { nome: "Gnonto", squadra: "FIORENTINA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 7, motivo: "FVM 9 Quot 7" },
  { nome: "Neres", squadra: "NAPOLI", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 5, motivo: "FVM 9 Quot 5" },
  { nome: "Braganca", squadra: "TORINO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 7, motivo: "FVM 9 Quot 7" },
  { nome: "Fitz-Jim", squadra: "TORINO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 6, motivo: "FVM 9 Quot 6" },
  { nome: "Bakola", squadra: "SASSUOLO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 8, motivo: "FVM 9 Quot 8" },
  { nome: "Ondrejka", squadra: "PARMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 5, motivo: "FVM 9 Quot 5" },
  { nome: "Casadei", squadra: "TORINO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 8, motivo: "FVM 9 Quot 8" },
  { nome: "Koopmeiners", squadra: "JUVENTUS", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 8, motivo: "FVM 9 Quot 8" },
  { nome: "Coulibaly L.", squadra: "LECCE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 10, motivo: "FVM 9 Quot 10" },
  { nome: "Elmas", squadra: "ATALANTA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 6, motivo: "FVM 9 Quot 6" },
  { nome: "Pasalic", squadra: "ATALANTA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 7, motivo: "FVM 9 Quot 7" },
  { nome: "Bracaglia", squadra: "FROSINONE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 9, motivo: "FVM 9 Quot 9" },
  { nome: "Kaiki", squadra: "COMO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 9, motivo: "FVM 9 Quot 9" },
  { nome: "Circati", squadra: "PARMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 6, motivo: "FVM 9 Quot 6" },
  { nome: "Lucumì", squadra: "JUVENTUS", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 8, motivo: "FVM 9 Quot 8" },
  { nome: "Spence", squadra: "INTER", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 10, motivo: "FVM 9 Quot 10" },
  { nome: "Vojvoda", squadra: "UDINESE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 8, motivo: "FVM 9 Quot 8" },
  { nome: "Balerdi", squadra: "ROMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 8, motivo: "FVM 9 Quot 8" },
  { nome: "Celik", squadra: "JUVENTUS", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 8, motivo: "FVM 9 Quot 8" },
  { nome: "Zortea", squadra: "BOLOGNA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 6, motivo: "FVM 9 Quot 6" },
  { nome: "Mina", squadra: "CAGLIARI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 9, quot: 9, motivo: "FVM 9 Quot 9" },
  { nome: "Lontani", squadra: "PARMA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 6, motivo: "FVM 8 Quot 6" },
  { nome: "Bonny", squadra: "INTER", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 8, motivo: "FVM 8 Quot 8" },
  { nome: "Geubbels", squadra: "LECCE", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 7, motivo: "FVM 8 Quot 7" },
  { nome: "Cutrone", squadra: "MONZA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 8, motivo: "FVM 8 Quot 8" },
  { nome: "Oulai", squadra: "FIORENTINA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 5, motivo: "FVM 8 Quot 5" },
  { nome: "Keita M.", squadra: "PARMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 6, motivo: "FVM 8 Quot 6" },
  { nome: "Mbangula", squadra: "BOLOGNA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 7, motivo: "FVM 8 Quot 7" },
  { nome: "Pierotti", squadra: "LECCE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 6, motivo: "FVM 8 Quot 6" },
  { nome: "Folorunsho", squadra: "MONZA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 3, motivo: "FVM 8 Quot 3" },
  { nome: "Sow", squadra: "GENOA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 7, motivo: "FVM 8 Quot 7" },
  { nome: "Colpani", squadra: "MONZA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 8, motivo: "FVM 8 Quot 8" },
  { nome: "Thuram K.", squadra: "JUVENTUS", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 8, motivo: "FVM 8 Quot 8" },
  { nome: "Musah", squadra: "MILAN", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 4, motivo: "FVM 8 Quot 4" },
  { nome: "Douglas Luiz", squadra: "JUVENTUS", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 4, motivo: "FVM 8 Quot 4" },
  { nome: "Rovella", squadra: "LAZIO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 6, motivo: "FVM 8 Quot 6" },
  { nome: "Nicolussi Caviglia", squadra: "PARMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 4, motivo: "FVM 8 Quot 4" },
  { nome: "Winks", squadra: "CAGLIARI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 8, motivo: "FVM 8 Quot 8" },
  { nome: "Loftus-Cheek", squadra: "MILAN", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 4, motivo: "FVM 8 Quot 4" },
  { nome: "Pessina", squadra: "MONZA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 5, motivo: "FVM 8 Quot 5" },
  { nome: "Matic", squadra: "SASSUOLO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 9, motivo: "FVM 8 Quot 9" },
  { nome: "Locatelli", squadra: "JUVENTUS", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 8, motivo: "FVM 8 Quot 8" },
  { nome: "Favasuli", squadra: "NAPOLI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 6, motivo: "FVM 8 Quot 6" },
  { nome: "Zè Pedro", squadra: "CAGLIARI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 8, motivo: "FVM 8 Quot 8" },
  { nome: "Norton-Cuffy", squadra: "GENOA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 8, motivo: "FVM 8 Quot 8" },
  { nome: "Obert", squadra: "CAGLIARI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 8, motivo: "FVM 8 Quot 8" },
  { nome: "Kamara H.", squadra: "UDINESE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 10, motivo: "FVM 8 Quot 10" },
  { nome: "Bellanova", squadra: "ATALANTA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 5, motivo: "FVM 8 Quot 5" },
  { nome: "Diego Carlos", squadra: "PARMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 8, motivo: "FVM 8 Quot 8" },
  { nome: "Marusic", squadra: "LAZIO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 5, motivo: "FVM 8 Quot 5" },
  { nome: "Djimsiti", squadra: "ATALANTA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 7, motivo: "FVM 8 Quot 7" },
  { nome: "Perri", squadra: "TORINO", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 8, quot: 9, motivo: "FVM 8 Quot 9" },
  { nome: "Robinson J.", squadra: "MONZA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 8, motivo: "FVM 7 Quot 8" },
  { nome: "Kulenovic", squadra: "TORINO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 6, motivo: "FVM 7 Quot 6" },
  { nome: "Hutchinson", squadra: "MILAN", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 7, motivo: "FVM 7 Quot 7" },
  { nome: "Perez K.", squadra: "VENEZIA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 5, motivo: "FVM 7 Quot 5" },
  { nome: "Masini", squadra: "FROSINONE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 7, motivo: "FVM 7 Quot 7" },
  { nome: "Unai Gomez", squadra: "UDINESE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 6, motivo: "FVM 7 Quot 6" },
  { nome: "Akinsanmiro", squadra: "MONZA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 8, motivo: "FVM 7 Quot 8" },
  { nome: "El Aynaoui", squadra: "ROMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 4, motivo: "FVM 7 Quot 4" },
  { nome: "Moro N.", squadra: "BOLOGNA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 5, motivo: "FVM 7 Quot 5" },
  { nome: "Ellertsson", squadra: "GENOA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 5, motivo: "FVM 7 Quot 5" },
  { nome: "Basic", squadra: "VENEZIA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 5, motivo: "FVM 7 Quot 5" },
  { nome: "Busio", squadra: "VENEZIA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 7, motivo: "FVM 7 Quot 7" },
  { nome: "Ilic", squadra: "LECCE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 4, motivo: "FVM 7 Quot 4" },
  { nome: "Odgaard", squadra: "BOLOGNA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 7, motivo: "FVM 7 Quot 7" },
  { nome: "Comert", squadra: "TORINO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 6, motivo: "FVM 7 Quot 6" },
  { nome: "Calvani", squadra: "FROSINONE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 8, motivo: "FVM 7 Quot 8" },
  { nome: "Viery", squadra: "FIORENTINA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 5, motivo: "FVM 7 Quot 5" },
  { nome: "Rodriguez Ju.", squadra: "CAGLIARI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 6, motivo: "FVM 7 Quot 6" },
  { nome: "Kouadio", squadra: "MONZA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 4, motivo: "FVM 7 Quot 4" },
  { nome: "Troilo", squadra: "PARMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 4, motivo: "FVM 7 Quot 4" },
  { nome: "Belghali", squadra: "TORINO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 7, motivo: "FVM 7 Quot 7" },
  { nome: "Bernasconi", squadra: "ATALANTA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 5, motivo: "FVM 7 Quot 5" },
  { nome: "Heggem", squadra: "BOLOGNA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 5, motivo: "FVM 7 Quot 5" },
  { nome: "Rensch", squadra: "ROMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 4, motivo: "FVM 7 Quot 4" },
  { nome: "Ahanor", squadra: "ATALANTA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 6, motivo: "FVM 7 Quot 6" },
  { nome: "Idzes", squadra: "SASSUOLO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 7, motivo: "FVM 7 Quot 7" },
  { nome: "Coco", squadra: "TORINO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 8, motivo: "FVM 7 Quot 8" },
  { nome: "Marin R.", squadra: "NAPOLI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 2, motivo: "FVM 7 Quot 2" },
  { nome: "Kristensen T.", squadra: "ATALANTA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 5, motivo: "FVM 7 Quot 5" },
  { nome: "Doekhi", squadra: "LAZIO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 8, motivo: "FVM 7 Quot 8" },
  { nome: "Abankwah", squadra: "UDINESE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 7, motivo: "FVM 7 Quot 7" },
  { nome: "Birindelli", squadra: "MONZA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 7, motivo: "FVM 7 Quot 7" },
  { nome: "Estupinan", squadra: "MILAN", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 4, motivo: "FVM 7 Quot 4" },
  { nome: "Stones", squadra: "INTER", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 11, motivo: "FVM 7 Quot 11" },
  { nome: "Zappacosta", squadra: "ATALANTA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 7, motivo: "FVM 7 Quot 7" },
  { nome: "Milinkovic-Savic V.", squadra: "NAPOLI", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 7, quot: 7, motivo: "FVM 7 Quot 7" },
  { nome: "Stulic", squadra: "LECCE", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 6, motivo: "FVM 6 Quot 6" },
  { nome: "Lang", squadra: "NAPOLI", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Camarda", squadra: "MILAN", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Lucca", squadra: "NAPOLI", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 3, motivo: "FVM 6 Quot 3" },
  { nome: "Vitinha O.", squadra: "GENOA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 7, motivo: "FVM 6 Quot 7" },
  { nome: "Massolin", squadra: "CAGLIARI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 3, motivo: "FVM 6 Quot 3" },
  { nome: "Mout", squadra: "MONZA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 1, motivo: "FVM 6 Quot 1" },
  { nome: "Amondarain", squadra: "BOLOGNA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Koutsoupias", squadra: "FROSINONE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Ngom", squadra: "LECCE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Gorter", squadra: "LECCE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 3, motivo: "FVM 6 Quot 3" },
  { nome: "Sorensen O.", squadra: "PARMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 3, motivo: "FVM 6 Quot 3" },
  { nome: "Miller L.", squadra: "UDINESE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Jashari", squadra: "MILAN", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Piotrowski", squadra: "UDINESE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 6, motivo: "FVM 6 Quot 6" },
  { nome: "Dominguez B.", squadra: "SASSUOLO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 5, motivo: "FVM 6 Quot 5" },
  { nome: "Fadera", squadra: "CAGLIARI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Fini", squadra: "FROSINONE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 5, motivo: "FVM 6 Quot 5" },
  { nome: "Oristanio", squadra: "TORINO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 6, motivo: "FVM 6 Quot 6" },
  { nome: "Almqvist", squadra: "PARMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 8, motivo: "FVM 6 Quot 8" },
  { nome: "Fabbian", squadra: "PARMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Gineitis", squadra: "TORINO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 5, motivo: "FVM 6 Quot 5" },
  { nome: "Berisha M.", squadra: "LECCE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Zerbin", squadra: "FROSINONE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 5, motivo: "FVM 6 Quot 5" },
  { nome: "Ricci S.", squadra: "COMO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 3, motivo: "FVM 6 Quot 3" },
  { nome: "Zalewski", squadra: "ATALANTA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 6, motivo: "FVM 6 Quot 6" },
  { nome: "Luis Henrique", squadra: "INTER", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 5, motivo: "FVM 6 Quot 5" },
  { nome: "Pobega", squadra: "BOLOGNA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 8, motivo: "FVM 6 Quot 8" },
  { nome: "Caqueret", squadra: "COMO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 6, motivo: "FVM 6 Quot 6" },
  { nome: "Adopo", squadra: "CAGLIARI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 9, motivo: "FVM 6 Quot 9" },
  { nome: "El Shaarawy", squadra: "GENOA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 7, motivo: "FVM 6 Quot 7" },
  { nome: "Pellegrini Lo.", squadra: "ROMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 8, motivo: "FVM 6 Quot 8" },
  { nome: "Cinquegrano", squadra: "SASSUOLO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 5, motivo: "FVM 6 Quot 5" },
  { nome: "Leysen F.", squadra: "SASSUOLO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 8, motivo: "FVM 6 Quot 8" },
  { nome: "Helland", squadra: "BOLOGNA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 5, motivo: "FVM 6 Quot 5" },
  { nome: "Britschgi", squadra: "PARMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Bella-Kotchap", squadra: "VENEZIA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Siebert", squadra: "LECCE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Joao Mario", squadra: "FIORENTINA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 2, motivo: "FVM 6 Quot 2" },
  { nome: "Floriani Mussolini", squadra: "LAZIO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 3, motivo: "FVM 6 Quot 3" },
  { nome: "Fortini", squadra: "TORINO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 6, motivo: "FVM 6 Quot 6" },
  { nome: "Provstgaard", squadra: "LAZIO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 5, motivo: "FVM 6 Quot 5" },
  { nome: "Veiga D.", squadra: "LECCE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 6, motivo: "FVM 6 Quot 6" },
  { nome: "Kempf", squadra: "COMO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 5, motivo: "FVM 6 Quot 5" },
  { nome: "Hainaut", squadra: "VENEZIA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 8, motivo: "FVM 6 Quot 8" },
  { nome: "Kelly L.", squadra: "JUVENTUS", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Marcandalli", squadra: "GENOA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 5, motivo: "FVM 6 Quot 5" },
  { nome: "Lucchesi", squadra: "MONZA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Gaspar K.", squadra: "LECCE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Bartesaghi", squadra: "MILAN", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 7, motivo: "FVM 6 Quot 7" },
  { nome: "Pedersen", squadra: "TORINO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 5, motivo: "FVM 6 Quot 5" },
  { nome: "Leite", squadra: "LAZIO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 6, motivo: "FVM 6 Quot 6" },
  { nome: "Doig", squadra: "SASSUOLO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 8, motivo: "FVM 6 Quot 8" },
  { nome: "Gatti", squadra: "JUVENTUS", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 5, motivo: "FVM 6 Quot 5" },
  { nome: "Cittadini", squadra: "FROSINONE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Holm", squadra: "BOLOGNA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 6, motivo: "FVM 6 Quot 6" },
  { nome: "Kossounou", squadra: "ATALANTA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 3, motivo: "FVM 6 Quot 3" },
  { nome: "Ismajli", squadra: "TORINO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 7, motivo: "FVM 6 Quot 7" },
  { nome: "Monterisi", squadra: "FROSINONE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 7, motivo: "FVM 6 Quot 7" },
  { nome: "Pedraza", squadra: "LAZIO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 5, motivo: "FVM 6 Quot 5" },
  { nome: "Angelino", squadra: "ROMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 3, motivo: "FVM 6 Quot 3" },
  { nome: "Gallo", squadra: "LECCE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 6, motivo: "FVM 6 Quot 6" },
  { nome: "Pavard", squadra: "INTER", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 5, motivo: "FVM 6 Quot 5" },
  { nome: "Caleta-Car", squadra: "SASSUOLO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 6, motivo: "FVM 6 Quot 6" },
  { nome: "Kolasinac", squadra: "ATALANTA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 6, motivo: "FVM 6 Quot 6" },
  { nome: "Delli Carri", squadra: "MONZA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 4, motivo: "FVM 6 Quot 4" },
  { nome: "Bijlow", squadra: "GENOA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 6, motivo: "FVM 6 Quot 6" },
  { nome: "Sanchez Ro.", squadra: "COMO", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 6, quot: 8, motivo: "FVM 6 Quot 8" },
  { nome: "Bobcek", squadra: "FROSINONE", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 8, motivo: "FVM 5 Quot 8" },
  { nome: "Rrahmani Al.", squadra: "VENEZIA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 6, motivo: "FVM 5 Quot 6" },
  { nome: "Elphege", squadra: "PARMA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 5, motivo: "FVM 5 Quot 5" },
  { nome: "Gueye", squadra: "UDINESE", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 7, motivo: "FVM 5 Quot 7" },
  { nome: "Gimenez", squadra: "MILAN", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 6, motivo: "FVM 5 Quot 6" },
  { nome: "NDri", squadra: "LECCE", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Dallinga", squadra: "BOLOGNA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 8, motivo: "FVM 5 Quot 8" },
  { nome: "Borrelli", squadra: "CAGLIARI", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Ngonge", squadra: "MONZA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Mota", squadra: "MONZA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 6, motivo: "FVM 5 Quot 6" },
  { nome: "Nzola", squadra: "CAGLIARI", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 3, motivo: "FVM 5 Quot 3" },
  { nome: "Zapata D.", squadra: "TORINO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 5, motivo: "FVM 5 Quot 5" },
  { nome: "Sierro", squadra: "PARMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 2, motivo: "FVM 5 Quot 2" },
  { nome: "Grillitsch", squadra: "FROSINONE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Cichella", squadra: "FROSINONE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Meichtry", squadra: "GENOA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Amorim", squadra: "GENOA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Gandelman", squadra: "LECCE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Tourè I.", squadra: "MONZA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Ordonez C.", squadra: "PARMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 3, motivo: "FVM 5 Quot 3" },
  { nome: "Addai", squadra: "COMO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Liberali", squadra: "COMO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 5, motivo: "FVM 5 Quot 5" },
  { nome: "El Azzouzi O.", squadra: "BOLOGNA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 2, motivo: "FVM 5 Quot 2" },
  { nome: "Sohm", squadra: "VENEZIA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 5, motivo: "FVM 5 Quot 5" },
  { nome: "Gilmour", squadra: "NAPOLI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 6, motivo: "FVM 5 Quot 6" },
  { nome: "Fofana Y.", squadra: "MILAN", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Traorè Hj.", squadra: "GENOA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Mkhitaryan", squadra: "INTER", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Deiola", squadra: "CAGLIARI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 5, motivo: "FVM 5 Quot 5" },
  { nome: "De Roon", squadra: "ROMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Sugawara", squadra: "CAGLIARI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 6, motivo: "FVM 5 Quot 6" },
  { nome: "Lulli", squadra: "ROMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 3, motivo: "FVM 5 Quot 3" },
  { nome: "Koulierakis", squadra: "ROMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 7, motivo: "FVM 5 Quot 7" },
  { nome: "Obrador", squadra: "SASSUOLO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 5, motivo: "FVM 5 Quot 5" },
  { nome: "Valdepenas", squadra: "FIORENTINA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 5, motivo: "FVM 5 Quot 5" },
  { nome: "Vitik", squadra: "BOLOGNA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Smolcic I.", squadra: "COMO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 3, motivo: "FVM 5 Quot 3" },
  { nome: "Schingtienne", squadra: "VENEZIA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 2, motivo: "FVM 5 Quot 2" },
  { nome: "Ghilardi", squadra: "ROMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 5, motivo: "FVM 5 Quot 5" },
  { nome: "Comuzzo", squadra: "TORINO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 7, motivo: "FVM 5 Quot 7" },
  { nome: "Oyono A.", squadra: "FROSINONE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 9, motivo: "FVM 5 Quot 9" },
  { nome: "Ehizibue", squadra: "GENOA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Hien", squadra: "ATALANTA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 6, motivo: "FVM 5 Quot 6" },
  { nome: "Olivera", squadra: "NAPOLI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Bertola", squadra: "UDINESE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Patterson", squadra: "TORINO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 5, motivo: "FVM 5 Quot 5" },
  { nome: "Drameh", squadra: "GENOA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 2, motivo: "FVM 5 Quot 2" },
  { nome: "Haps", squadra: "VENEZIA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 5, motivo: "FVM 5 Quot 5" },
  { nome: "Zanoli", squadra: "UDINESE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 5, motivo: "FVM 5 Quot 5" },
  { nome: "Cambiaso", squadra: "JUVENTUS", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 7, motivo: "FVM 5 Quot 7" },
  { nome: "Mazzocchi", squadra: "VENEZIA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 1, motivo: "FVM 5 Quot 1" },
  { nome: "Parisi", squadra: "FIORENTINA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Valenti", squadra: "PARMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 3, motivo: "FVM 5 Quot 3" },
  { nome: "Carboni A.", squadra: "MONZA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Gabbia", squadra: "MILAN", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 6, motivo: "FVM 5 Quot 6" },
  { nome: "Ranieri L.", squadra: "FIORENTINA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 3, motivo: "FVM 5 Quot 3" },
  { nome: "Walukiewicz", squadra: "SASSUOLO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 3, motivo: "FVM 5 Quot 3" },
  { nome: "Kabasele", squadra: "UDINESE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 3, motivo: "FVM 5 Quot 3" },
  { nome: "Buongiorno", squadra: "NAPOLI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 5, motivo: "FVM 5 Quot 5" },
  { nome: "Rodriguez R.", squadra: "TORINO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 5, motivo: "FVM 5 Quot 5" },
  { nome: "Juan Jesus", squadra: "VENEZIA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Corvi", squadra: "PARMA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 4, motivo: "FVM 5 Quot 4" },
  { nome: "Di Gregorio", squadra: "JUVENTUS", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 9, motivo: "FVM 5 Quot 9" },
  { nome: "Muric", squadra: "SASSUOLO", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 5, quot: 5, motivo: "FVM 5 Quot 5" },
  { nome: "Fatah", squadra: "LECCE", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 5, motivo: "FVM 4 Quot 5" },
  { nome: "Mutandwa", squadra: "CAGLIARI", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 6, motivo: "FVM 4 Quot 6" },
  { nome: "Morata", squadra: "COMO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 4, motivo: "FVM 4 Quot 4" },
  { nome: "Diallo O.", squadra: "PARMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 3, motivo: "FVM 4 Quot 3" },
  { nome: "Fernandez T.", squadra: "VENEZIA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 3, motivo: "FVM 4 Quot 3" },
  { nome: "Felici", squadra: "CAGLIARI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 4, motivo: "FVM 4 Quot 4" },
  { nome: "Dele-Bashiru", squadra: "LAZIO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 4, motivo: "FVM 4 Quot 4" },
  { nome: "Stankovic A.", squadra: "INTER", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 2, motivo: "FVM 4 Quot 2" },
  { nome: "Prati", squadra: "CAGLIARI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 4, motivo: "FVM 4 Quot 4" },
  { nome: "Sulemana I.", squadra: "SASSUOLO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 3, motivo: "FVM 4 Quot 3" },
  { nome: "Ilkhan", squadra: "TORINO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 4, motivo: "FVM 4 Quot 4" },
  { nome: "Miretti", squadra: "JUVENTUS", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 3, motivo: "FVM 4 Quot 3" },
  { nome: "Maleh", squadra: "LECCE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 4, motivo: "FVM 4 Quot 4" },
  { nome: "Messias", squadra: "GENOA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 7, motivo: "FVM 4 Quot 7" },
  { nome: "Brescianini", squadra: "FIORENTINA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 3, motivo: "FVM 4 Quot 3" },
  { nome: "Gagliardini", squadra: "CAGLIARI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 3, motivo: "FVM 4 Quot 3" },
  { nome: "Cataldi", squadra: "LAZIO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 3, motivo: "FVM 4 Quot 3" },
  { nome: "Halhal", squadra: "VENEZIA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 2, motivo: "FVM 4 Quot 2" },
  { nome: "Mitaj", squadra: "GENOA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 3, motivo: "FVM 4 Quot 3" },
  { nome: "Cuenca A.", squadra: "COMO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 1, motivo: "FVM 4 Quot 1" },
  { nome: "Arizala", squadra: "UDINESE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 3, motivo: "FVM 4 Quot 3" },
  { nome: "Ziolkowski", squadra: "MONZA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 1, motivo: "FVM 4 Quot 1" },
  { nome: "Athekame", squadra: "MILAN", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 3, motivo: "FVM 4 Quot 3" },
  { nome: "Ndiaye", squadra: "PARMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 1, motivo: "FVM 4 Quot 1" },
  { nome: "Palma", squadra: "UDINESE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 2, motivo: "FVM 4 Quot 2" },
  { nome: "Sverko", squadra: "VENEZIA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 2, motivo: "FVM 4 Quot 2" },
  { nome: "Beukema", squadra: "NAPOLI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 4, motivo: "FVM 4 Quot 4" },
  { nome: "Dodò", squadra: "FIORENTINA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 8, motivo: "FVM 4 Quot 8" },
  { nome: "Pongracic", squadra: "FIORENTINA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 3, motivo: "FVM 4 Quot 3" },
  { nome: "Correia T.", squadra: "VENEZIA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 6, motivo: "FVM 4 Quot 6" },
  { nome: "Tomori", squadra: "MILAN", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 5, motivo: "FVM 4 Quot 5" },
  { nome: "Badiashile", squadra: "NAPOLI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 6, motivo: "FVM 4 Quot 6" },
  { nome: "Zappa", squadra: "CAGLIARI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 4, motivo: "FVM 4 Quot 4" },
  { nome: "Pellegrini Lu.", squadra: "LAZIO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 1, motivo: "FVM 4 Quot 1" },
  { nome: "Martin", squadra: "GENOA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 4, motivo: "FVM 4 Quot 4" },
  { nome: "Tornqvist", squadra: "MONZA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 3, motivo: "FVM 4 Quot 3" },
  { nome: "Stankovic F.", squadra: "VENEZIA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 4, quot: 5, motivo: "FVM 4 Quot 5" },
  { nome: "Frigan", squadra: "PARMA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 4, motivo: "FVM 3 Quot 4" },
  { nome: "Kuhn", squadra: "COMO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 3, motivo: "FVM 3 Quot 3" },
  { nome: "Ekhator", squadra: "JUVENTUS", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 2, motivo: "FVM 3 Quot 2" },
  { nome: "Petagna", squadra: "MONZA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 2, motivo: "FVM 3 Quot 2" },
  { nome: "Chakvetadze", squadra: "UDINESE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 3, motivo: "FVM 3 Quot 3" },
  { nome: "Przyborek", squadra: "LAZIO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 1, motivo: "FVM 3 Quot 1" },
  { nome: "Aboukhlal", squadra: "TORINO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 2, motivo: "FVM 3 Quot 2" },
  { nome: "Jovanovic", squadra: "UDINESE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 1, motivo: "FVM 3 Quot 1" },
  { nome: "Hasa", squadra: "FROSINONE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 3, motivo: "FVM 3 Quot 3" },
  { nome: "Lipani", squadra: "SASSUOLO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 3, motivo: "FVM 3 Quot 3" },
  { nome: "Gelli F.", squadra: "FROSINONE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 2, motivo: "FVM 3 Quot 2" },
  { nome: "Boloca", squadra: "SASSUOLO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 1, motivo: "FVM 3 Quot 1" },
  { nome: "Ciurria", squadra: "MONZA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 1, motivo: "FVM 3 Quot 1" },
  { nome: "Tchato", squadra: "FROSINONE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 2, motivo: "FVM 3 Quot 2" },
  { nome: "Aurelio", squadra: "CAGLIARI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 1, motivo: "FVM 3 Quot 1" },
  { nome: "Akpoguma", squadra: "FROSINONE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 2, motivo: "FVM 3 Quot 2" },
  { nome: "Alhassane", squadra: "BOLOGNA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 2, motivo: "FVM 3 Quot 2" },
  { nome: "Franjic", squadra: "VENEZIA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 2, motivo: "FVM 3 Quot 2" },
  { nome: "Ndaba", squadra: "LECCE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 1, motivo: "FVM 3 Quot 1" },
  { nome: "Odenthal", squadra: "SASSUOLO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 3, motivo: "FVM 3 Quot 3" },
  { nome: "Candè", squadra: "SASSUOLO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 2, motivo: "FVM 3 Quot 2" },
  { nome: "Otoa", squadra: "GENOA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 2, motivo: "FVM 3 Quot 2" },
  { nome: "Van Der Brempt", squadra: "SASSUOLO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 1, motivo: "FVM 3 Quot 1" },
  { nome: "Moreno M.", squadra: "VENEZIA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 4, motivo: "FVM 3 Quot 4" },
  { nome: "Kambwala", squadra: "COMO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 2, motivo: "FVM 3 Quot 2" },
  { nome: "Goglichidze", squadra: "MONZA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 1, motivo: "FVM 3 Quot 1" },
  { nome: "Ebosse", squadra: "UDINESE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 3, motivo: "FVM 3 Quot 3" },
  { nome: "Casale", squadra: "BOLOGNA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 2, motivo: "FVM 3 Quot 2" },
  { nome: "Terzic", squadra: "FROSINONE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 4, motivo: "FVM 3 Quot 4" },
  { nome: "Lazzari", squadra: "LAZIO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 1, motivo: "FVM 3 Quot 1" },
  { nome: "Sabelli", squadra: "GENOA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 2, motivo: "FVM 3 Quot 2" },
  { nome: "Biraghi", squadra: "TORINO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 1, motivo: "FVM 3 Quot 1" },
  { nome: "Provedel", squadra: "INTER", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 1, motivo: "FVM 3 Quot 1" },
  { nome: "Perin", squadra: "JUVENTUS", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 3, quot: 6, motivo: "FVM 3 Quot 6" },
  { nome: "Esteban", squadra: "LECCE", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 2, motivo: "FVM 2 Quot 2" },
  { nome: "Enem", squadra: "BOLOGNA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 1, motivo: "FVM 2 Quot 1" },
  { nome: "Birligea", squadra: "FROSINONE", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 4, motivo: "FVM 2 Quot 4" },
  { nome: "Havel", squadra: "GENOA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 3, motivo: "FVM 2 Quot 3" },
  { nome: "Buksa", squadra: "UDINESE", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 2, motivo: "FVM 2 Quot 2" },
  { nome: "Bayo V.", squadra: "UDINESE", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 2, motivo: "FVM 2 Quot 2" },
  { nome: "Vaz", squadra: "ROMA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 1, motivo: "FVM 2 Quot 1" },
  { nome: "Sulemana K.", squadra: "ATALANTA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 4, motivo: "FVM 2 Quot 4" },
  { nome: "Adorante", squadra: "VENEZIA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 4, motivo: "FVM 2 Quot 4" },
  { nome: "Foe Ondoa", squadra: "MONZA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 2, motivo: "FVM 2 Quot 2" },
  { nome: "Colombo L.", squadra: "MONZA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 2, motivo: "FVM 2 Quot 2" },
  { nome: "Camara A.", squadra: "UDINESE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 1, motivo: "FVM 2 Quot 1" },
  { nome: "Cremaschi", squadra: "PARMA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 2, motivo: "FVM 2 Quot 2" },
  { nome: "Venturino", squadra: "GENOA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 1, motivo: "FVM 2 Quot 1" },
  { nome: "Anjorin", squadra: "TORINO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 1, motivo: "FVM 2 Quot 1" },
  { nome: "Zarraga", squadra: "UDINESE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 1, motivo: "FVM 2 Quot 1" },
  { nome: "Belahyane", squadra: "LAZIO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 5, motivo: "FVM 2 Quot 5" },
  { nome: "Helgason", squadra: "VENEZIA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 2, motivo: "FVM 2 Quot 2" },
  { nome: "Kone B.", squadra: "FROSINONE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 1, motivo: "FVM 2 Quot 1" },
  { nome: "Bjarkason", squadra: "VENEZIA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 1, motivo: "FVM 2 Quot 1" },
  { nome: "Duncan", squadra: "VENEZIA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 1, motivo: "FVM 2 Quot 1" },
  { nome: "Kofler", squadra: "CAGLIARI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 5, motivo: "FVM 2 Quot 5" },
  { nome: "Diawara S.", squadra: "MILAN", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 1, motivo: "FVM 2 Quot 1" },
  { nome: "Bakoune", squadra: "MONZA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 4, motivo: "FVM 2 Quot 4" },
  { nome: "Puczka", squadra: "GENOA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 2, motivo: "FVM 2 Quot 2" },
  { nome: "Mlacic", squadra: "UDINESE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 1, motivo: "FVM 2 Quot 1" },
  { nome: "Idrissi R.", squadra: "CAGLIARI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 2, motivo: "FVM 2 Quot 2" },
  { nome: "Jean", squadra: "LECCE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 1, motivo: "FVM 2 Quot 1" },
  { nome: "Marianucci", squadra: "NAPOLI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 1, motivo: "FVM 2 Quot 1" },
  { nome: "Sagrado", squadra: "VENEZIA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 3, motivo: "FVM 2 Quot 3" },
  { nome: "Carboni F.", squadra: "PARMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 1, motivo: "FVM 2 Quot 1" },
  { nome: "Cabal", squadra: "JUVENTUS", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 1, motivo: "FVM 2 Quot 1" },
  { nome: "Terracciano F.", squadra: "MILAN", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 1, motivo: "FVM 2 Quot 1" },
  { nome: "De Silvestri", squadra: "BOLOGNA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 2, motivo: "FVM 2 Quot 2" },
  { nome: "Rugani", squadra: "JUVENTUS", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 1, motivo: "FVM 2 Quot 1" },
  { nome: "Thiam", squadra: "MONZA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 2, quot: 3, motivo: "FVM 2 Quot 3" },
  { nome: "Robinho Junior", squadra: "GENOA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "De Martis", squadra: "PARMA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Lauberbach", squadra: "VENEZIA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 2, motivo: "FVM 1 Quot 2" },
  { nome: "Lisman", squadra: "VENEZIA", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Albarracin", squadra: "CAGLIARI", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Trepy", squadra: "CAGLIARI", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Giovane", squadra: "NAPOLI", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 3, motivo: "FVM 1 Quot 3" },
  { nome: "Moro L.", squadra: "SASSUOLO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Azon", squadra: "COMO", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Milik", squadra: "JUVENTUS", ruolo: "A", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 4, motivo: "FVM 1 Quot 4" },
  { nome: "Libra", squadra: "BOLOGNA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Comotto", squadra: "MILAN", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Laerke", squadra: "LECCE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Dagasso", squadra: "VENEZIA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "El Azzouzi A.", squadra: "FROSINONE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Lahdo", squadra: "COMO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Fofana Sa.", squadra: "LECCE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Liteta", squadra: "CAGLIARI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Iannoni", squadra: "SASSUOLO", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Forson O.", squadra: "MONZA", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 2, motivo: "FVM 1 Quot 2" },
  { nome: "Kaba", squadra: "LECCE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 2, motivo: "FVM 1 Quot 2" },
  { nome: "Lovric", squadra: "UDINESE", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Ciervo", squadra: "CAGLIARI", ruolo: "C", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Drobnic", squadra: "PARMA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 2, motivo: "FVM 1 Quot 2" },
  { nome: "Maye", squadra: "MONZA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Omar Fayed", squadra: "FROSINONE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Corrado", squadra: "FROSINONE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Oyono J.", squadra: "FROSINONE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Gelli J.", squadra: "FROSINONE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Gomes", squadra: "VENEZIA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Macchioni", squadra: "SASSUOLO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Raterink", squadra: "CAGLIARI", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Perez M.", squadra: "LECCE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Pieragnolo", squadra: "SASSUOLO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Dembelè A.", squadra: "LECCE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Vogliacco", squadra: "GENOA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Matturro", squadra: "GENOA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Missori", squadra: "SASSUOLO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Amey", squadra: "FROSINONE", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Antov", squadra: "MONZA", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Goldaniga", squadra: "COMO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Patric", squadra: "LAZIO", ruolo: "D", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Pompei", squadra: "ATALANTA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Mrozek", squadra: "UDINESE", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Grabara", squadra: "JUVENTUS", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Pisseri", squadra: "FROSINONE", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Penev", squadra: "LECCE", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Vismara", squadra: "ATALANTA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Renzetti", squadra: "LAZIO", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Happonen", squadra: "BOLOGNA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Pozzi", squadra: "VENEZIA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Strajnar", squadra: "MONZA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Lolic", squadra: "FROSINONE", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Desplanches", squadra: "FROSINONE", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Mascardi", squadra: "TORINO", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Daffara", squadra: "PARMA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 5, motivo: "FVM 1 Quot 5" },
  { nome: "Siviero", squadra: "TORINO", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Motta", squadra: "LAZIO", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Pessina Mas.", squadra: "BOLOGNA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "De Marzi", squadra: "ROMA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Torriani", squadra: "MILAN", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Pizzignacco", squadra: "MONZA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Grandi", squadra: "VENEZIA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Sherri", squadra: "CAGLIARI", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Stolz", squadra: "GENOA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Samooja", squadra: "LECCE", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Christensen O.", squadra: "FIORENTINA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Piana", squadra: "UDINESE", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Paleari", squadra: "TORINO", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Montipò", squadra: "VENEZIA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Ciocci", squadra: "CAGLIARI", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Turati", squadra: "SASSUOLO", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Russo A.", squadra: "SASSUOLO", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Bleve", squadra: "LECCE", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Ghidotti", squadra: "PARMA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Contini", squadra: "NAPOLI", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Terracciano", squadra: "MILAN", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Vigorito", squadra: "COMO", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Fruchtl", squadra: "LECCE", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Rossi F.", squadra: "ATALANTA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Satalino", squadra: "SASSUOLO", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Pinsoglio", squadra: "JUVENTUS", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Di Gennaro", squadra: "INTER", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Gollini", squadra: "ROMA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Padelli", squadra: "UDINESE", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Neto", squadra: "JUVENTUS", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Sommariva", squadra: "GENOA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Lezzerini", squadra: "FIORENTINA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Sportiello", squadra: "ATALANTA", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
  { nome: "Radunovic", squadra: "CAGLIARI", ruolo: "P", G:0 A:0 Pv:0 Mv:6 Fm:6 xA:0, hype: 20, fvm: 1, quot: 1, motivo: "FVM 1 Quot 1" },
];
